# Generated by Django 2.1.3 on 2018-11-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contact',
            new_name='contacts',
        ),
    ]
