# Generated by Django 2.1.2 on 2018-11-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181110_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='items',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='orders',
            new_name='order',
        ),
    ]
