# Generated by Django 2.1.2 on 2019-03-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181214_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='avg_orders',
            new_name='avg_monthly_orders',
        ),
    ]
