# Generated by Django 2.1.2 on 2019-03-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190322_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order', through='api.OrderItem', to='api.Item'),
        ),
    ]
