# Generated by Django 2.1.2 on 2019-04-05 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190405_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('previous_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_state', to='api.State')),
            ],
        ),
    ]
