# Generated by Django 2.1.2 on 2019-04-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_state_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
