# Generated by Django 2.1.2 on 2019-06-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_apiuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='delivery_reliability',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='low_stock_threshold',
            field=models.IntegerField(null=True),
        ),
    ]
